# Generated by Django 4.2.3 on 2023-07-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhar_card",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_address",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_choice",
            field=models.CharField(choices=[], default="", max_length=25),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="pancard",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="permanent_address",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
