# Generated by Django 4.2.3 on 2023-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_aadhar_card_user_current_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="employee_choice",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("buyer", "buyer"), ("seller", "seller")],
                default="",
                max_length=25,
            ),
        ),
    ]
