# Generated by Django 4.2.3 on 2023-07-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_employee_choice_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("buyer", "buyer"), ("seller", "seller"), ("both", "both")],
                default="",
                max_length=25,
            ),
        ),
    ]
