# Generated by Django 4.2.3 on 2023-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="whatsapp_verified",
            new_name="email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_completeness",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="whatsapp_otp",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
    ]
