# Generated by Django 4.2.3 on 2023-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_rename_whatsapp_verified_user_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
