# Generated by Django 4.2.3 on 2023-08-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_customgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_otp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
