# Generated by Django 4.2.3 on 2023-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_customgroup_created_at_customgroup_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgroup",
            name="sequence",
            field=models.PositiveIntegerField(),
        ),
    ]
